# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
a = np.random.random([3,3,3])
a

array([[[0.88494759, 0.78602689, 0.89195172],
        [0.36509415, 0.28607772, 0.72176047],
        [0.31241241, 0.63190091, 0.2308009 ]],

       [[0.46197128, 0.03768328, 0.37507802],
        [0.01236577, 0.3593783 , 0.27009088],
        [0.59364573, 0.0482952 , 0.52238143]],

       [[0.27773254, 0.36652726, 0.78024794],
        [0.53462434, 0.14579928, 0.39749963],
        [0.81881859, 0.12198502, 0.83949837]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [8]:
c = np.diag(1+np.arange(4),-1)
c

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [17]:
b = np.zeros((8,8))
b[::2,::2]=1
b[1::2,1::2]=1
b

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

# 4. Normalize a 5x5 random matrix

In [31]:
arr= np.random.random((3,3))
print("Original Array:")
print(arr)
arrmax, arrmin = arr.max(), arr.min()
arr = (arr - arrmin)/(arrmax - arrmin)
print("After normalization:")
print(arr)

Original Array:
[[0.68737435 0.50440363 0.07963524]
 [0.21773666 0.95046026 0.81938624]
 [0.74159853 0.54903607 0.94234287]]
After normalization:
[[0.69788889 0.48777697 0.        ]
 [0.15858687 1.         0.84948293]
 [0.76015648 0.53903002 0.9906785 ]]


# 5.  How to find common values between two arrays?

In [32]:
arr1 = np.array([[1,2,3],[4,5,6],[20,9,19]])
arr2 = np.array([[5,7,8],[2,9,3]])
print(np.intersect1d(arr1,arr2))

[2 3 5 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [29]:
today = np.datetime64('today','D')
print('Today: ',today)
yesterday = np.datetime64('today','D')-np.timedelta64(1,'D')
print('Yesterday: ',yesterday)
tomorrow = np.datetime64('today','D')+np.timedelta64(1,'D')
print('Tomorrow: ',tomorrow)

Today:  2020-07-28
Yesterday:  2020-07-27
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [27]:
arr1 = np.random.random([3,3])
arr2 = np.random.random([3,3])
print('First array:')
print(arr1)
print('Second array:')
print(arr2)
arr = np.allclose(arr1,arr2)
print(arr)

First array:
[[0.30299998 0.7486911  0.89529964]
 [0.26251137 0.46824798 0.30016331]
 [0.96324767 0.09516078 0.32064911]]
Second array:
[[0.83561178 0.8196405  0.59288443]
 [0.94867336 0.18004307 0.49315824]
 [0.8235465  0.13609836 0.60255335]]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [39]:
a = np.random.random([10])
print(a)
a[a.argmax()]=0
print(a)

[0.42001087 0.64167222 0.20997295 0.80747088 0.12405348 0.8504486
 0.21130086 0.99279772 0.11254598 0.58767259]
[0.42001087 0.64167222 0.20997295 0.80747088 0.12405348 0.8504486
 0.21130086 0.         0.11254598 0.58767259]


# 9. How to print all the values of an array?

In [42]:
a = np.random.random([3,3])
print(a)

[[0.5579666  0.5995667  0.14962737]
 [0.47880677 0.71730119 0.99740663]
 [0.678238   0.99439888 0.54408323]]


# 10.Subtract the mean of each row of a matrix

In [45]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
m = 0
for i in range(len(a)) :
    m = a[i,:].mean()
    a[i,:] = a[i,:]- m
print(a)    

[[1 2 3]
 [4 5 6]]
[[-1  0  1]
 [-1  0  1]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [46]:
Z = np.ones(10)
print('Z:',Z)
I = np.random.randint(0,len(Z),20)
print('I:',I)
Z += np.bincount(I, minlength=len(Z))
print(Z)

Z: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
I: [1 4 2 3 7 1 7 5 9 3 4 0 5 9 4 0 3 1 8 1]
[3. 5. 2. 4. 4. 3. 1. 3. 2. 3.]


# 12.How to get the diagonal of a dot product?

In [49]:
a = np.random.randint(0,10,(3,3))
print(a)
b = np.random.randint(0,10,(3,3))
print(b)
c = np.diag(np.dot(a,b))
c

[[0 8 0]
 [1 2 8]
 [6 9 7]]
[[4 6 8]
 [4 5 7]
 [2 6 6]]
[[ 32  40  56]
 [ 28  64  70]
 [ 74 123 153]]


array([ 32,  64, 153])

# 13.How to find the most frequent value in an array?

In [50]:
x = np.random.randint(1,10,10)
print(x)
print(np.bincount(x).argmax())

[3 8 9 2 3 9 3 9 7 8]
3


# 14.How to get the n largest values of an array

In [58]:
x = np.random.randint(1,5,5)
print("Original array:")
print(x)
n = 2
print('n =',n)
print (x[np.argsort(x)[-n:]])

Original array:
[1 4 3 4 4]
n = 2
[4 4]


# 15.How to create a record array from a regular array?

In [53]:
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])

result= np.core.records.fromarrays([a1, a2, a3])
print(result)

[(1, 'Red', 12.2) (2, 'Green', 15. ) (3, 'White', 20. )
 (4, 'Orange', 40. )]
